### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ycpatel813** [jforaker/react-accordion-with-header#1]
Hi,
I found this is a very awesome library but got error when I want to use in React+Meteor Project.

![2017-05-15_1919](https://cloud.githubusercontent.com/assets/8921044/26060725/8ae5bffa-39a3-11e7-972a-f5eb47c00a29.png)

Thank you.

**Comment by jforaker** [comment]
Are you trying to render on the server?  I don't call `document` anywhere.

Actually, looks like it is caused by the `'insert-css'` library, which appends a stylesheet to the [head](https://github.com/substack/insert-css/blob/master/index.js#L14) of `document`.

I made this lib before all the cool tech like `styled-components` so maybe thats not the best tool for the job?  I'd like to refactor it to use styled-components, but not too much free time now. Always up for a PR :)

**Comment by jforaker** [comment]
@ycpatel813 - I've updated the package to remove `insert-css`, you can download the latest version from npm 

`npm i react-accordion-with-header --save`

Let me know if it solves your problem. If it doesn't, I reckon its something to do with the way meteor is trying to render it without a window/document.

**Comment by ronak-thakkar** [comment]
Hello jforaker, 
Thanks for answer, I am not using on  server. I am try to use in react-meteor application and my import statement on ReactJs side.

Thanks for update, I try with new update and let you know for issue.
